### ISSUE TITLE
struggling with my manual qsfs setup

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/0-stor_v2#93]
I'm trying to set up qsfs locally, and configure it to use a zdbs backend deployed on the grid.
The reason for the manual setup is to get familiar with the qsfs and its components and configurations.
 
 I had successfully installed all requirements and built all binaries based on the docs available on zdb, zdbfs, 0-stor_v2 repos.

I have deployed 8 zdbs on the grid using the ts grid client, 4 run in user key mode for the meta store, and the rest run in seq mode for the data store.

Here are the steps I'm using to bootstrap the system
1 - lunching zstor using:
```sh
sudo zstor_v2 monitor
```
with this configuration file `zstor_config.toml`
```sh
minimal_shards = 3
expected_shards = 4
redundant_groups = 0
redundant_nodes = 0
socket = "/tmp/zstor.sock"
prometheus_port = 9100
zdbfs_mountpoint = "/mnt/zdbfs"
zdb_data_dir_path = "/home/sameh/zdb_temp/zdb-data/zdbfs-data"
max_zdb_data_dir_size = 5600

[encryption]
algorithm = "AES"
key = "4d778ba3216e4da4231540c92a55f06157cabba802f9b68fb0f78375d2e825af"

[compression]
algorithm = "snappy"

[meta]
type = "zdb"

[meta.config]
prefix = "hamada"

[meta.config.encryption]
algorithm = "AES"
key = "4d778ba3216e4da4231540c92a55f06157cabba802f9b68fb0f78375d2e825af"

[[meta.config.backends]]
address = "[302:9e63:7d43:b742:469d:3ec2:ab15:f75e]:9900"
namespace = "41-7478-hamada2"
password = "testzdb"

[[meta.config.backends]]
address = "[301:b989:8977:ff23:3f30:ee86:fc5b:ecd7]:9900"
namespace = "41-7479-hamada1"
password = "testzdb"

[[meta.config.backends]]
address = "[300:487a:7ea1:5b4e:e244:ef5d:6f66:1670]:9900"
namespace = "41-7480-hamada3"
password = "testzdb"

[[meta.config.backends]]
address = "[300:68f9:dc9f:d10e:52d4:bc1f:308e:4bbb]:9900"
namespace = "41-7482-hamada0"
password = "testzdb"

[[groups]]
[[groups.backends]]
address = "[302:9e63:7d43:b742:469d:3ec2:ab15:f75e]:9900"
namespace = "41-7496-hamada1"
password = "testzdb"

[[groups.backends]]
address = "[301:b989:8977:ff23:3f30:ee86:fc5b:ecd7]:9900"
namespace = "41-7499-hamada3"
password = "testzdb"

[[groups]]
[[groups.backends]]
address = "[300:487a:7ea1:5b4e:e244:ef5d:6f66:1670]:9900"
namespace = "41-7500-hamada0"
password = "testzdb"

[[groups.backends]]
address = "[301:1037:16ee:23fb:b621:474b:4dc:c34b]:9900"
namespace = "41-7502-hamada2"
password = "testzdb"
``` 

no errors show, and here is the zstor.log content after zstor started 

```sh
2022-09-05 17:22:17 +02:00: DEBUG connecting to zdb at [302:9e63:7d43:b742:469d:3ec2:ab15:f75e]:9900
2022-09-05 17:22:17 +02:00: DEBUG connecting to zdb at [301:b989:8977:ff23:3f30:ee86:fc5b:ecd7]:9900
2022-09-05 17:22:17 +02:00: DEBUG connecting to zdb at [300:487a:7ea1:5b4e:e244:ef5d:6f66:1670]:9900
2022-09-05 17:22:17 +02:00: DEBUG connecting to zdb at [300:68f9:dc9f:d10e:52d4:bc1f:308e:4bbb]:9900
2022-09-05 17:22:19 +02:00: WARN NopExplorer started, automatic capacity managment is disabled
2022-09-05 17:22:19 +02:00: DEBUG Backend manager actor started, loading backends to monitor
2022-09-05 17:22:19 +02:00: DEBUG connecting to zdb at [302:9e63:7d43:b742:469d:3ec2:ab15:f75e]:9900
2022-09-05 17:22:19 +02:00: DEBUG checking old pid error error during accessing local storage for No such file or directory (os error 2): No such file or directory (os error 2)
2022-09-05 17:22:20 +02:00: DEBUG connecting to zdb at [301:b989:8977:ff23:3f30:ee86:fc5b:ecd7]:9900
2022-09-05 17:22:20 +02:00: DEBUG connecting to zdb at [300:487a:7ea1:5b4e:e244:ef5d:6f66:1670]:9900
2022-09-05 17:22:20 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:21 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:22 +02:00: DEBUG connecting to zdb at [301:1037:16ee:23fb:b621:474b:4dc:c34b]:9900
2022-09-05 17:22:22 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:23 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:24 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:25 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:26 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:27 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:28 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:29 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:30 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:31 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:32 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:33 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:34 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:35 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:36 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:37 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:38 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:39 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:40 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:41 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:42 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:43 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:44 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:45 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:46 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:47 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:48 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:49 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:50 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:51 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:52 +02:00: WARN Could not connect to backend [301:1037:16ee:23fb:b621:474b:4dc:c34b]:9900 41-7502-hamada2 in config file: ZDB at [301:1037:16ee:23fb:b621:474b:4dc:c34b]:9900 41-7502-hamada2, error operation CONNECT caused by timeout
2022-09-05 17:22:52 +02:00: DEBUG connecting to zdb at [302:9e63:7d43:b742:469d:3ec2:ab15:f75e]:9900
2022-09-05 17:22:52 +02:00: DEBUG connecting to zdb at [301:b989:8977:ff23:3f30:ee86:fc5b:ecd7]:9900
2022-09-05 17:22:52 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:53 +02:00: DEBUG connecting to zdb at [300:487a:7ea1:5b4e:e244:ef5d:6f66:1670]:9900
2022-09-05 17:22:53 +02:00: DEBUG connecting to zdb at [300:68f9:dc9f:d10e:52d4:bc1f:308e:4bbb]:9900
2022-09-05 17:22:53 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:54 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:55 +02:00: DEBUG connecting to zdb at [301:1037:16ee:23fb:b621:474b:4dc:c34b]:9900
2022-09-05 17:22:55 +02:00: DEBUG connecting to zdb at [301:1037:16ee:23fb:b621:474b:4dc:c34b]:9900
2022-09-05 17:22:55 +02:00: DEBUG connecting to zdb at [301:1037:16ee:23fb:b621:474b:4dc:c34b]:9900
2022-09-05 17:22:55 +02:00: DEBUG connecting to zdb at [301:1037:16ee:23fb:b621:474b:4dc:c34b]:9900
2022-09-05 17:22:55 +02:00: DEBUG connecting to zdb at [301:1037:16ee:23fb:b621:474b:4dc:c34b]:9900
2022-09-05 17:22:55 +02:00: DEBUG connecting to zdb at [301:1037:16ee:23fb:b621:474b:4dc:c34b]:9900
2022-09-05 17:22:55 +02:00: DEBUG connecting to zdb at [301:1037:16ee:23fb:b621:474b:4dc:c34b]:9900
2022-09-05 17:22:55 +02:00: DEBUG connecting to zdb at [301:1037:16ee:23fb:b621:474b:4dc:c34b]:9900
2022-09-05 17:22:55 +02:00: DEBUG connecting to zdb at [301:1037:16ee:23fb:b621:474b:4dc:c34b]:9900
2022-09-05 17:22:55 +02:00: DEBUG connecting to zdb at [301:1037:16ee:23fb:b621:474b:4dc:c34b]:9900
2022-09-05 17:22:55 +02:00: DEBUG connecting to zdb at [301:1037:16ee:23fb:b621:474b:4dc:c34b]:9900
2022-09-05 17:22:55 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:55 +02:00: DEBUG connecting to zdb at [301:1037:16ee:23fb:b621:474b:4dc:c34b]:9900
2022-09-05 17:22:56 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:57 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:58 +02:00: DEBUG connecting to zdb at [301:1037:16ee:23fb:b621:474b:4dc:c34b]:9900
2022-09-05 17:22:58 +02:00: DEBUG renewing stats fd
2022-09-05 17:22:59 +02:00: DEBUG renewing stats fd
2022-09-05 17:23:00 +02:00: DEBUG renewing stats fd
2022-09-05 17:23:01 +02:00: DEBUG connecting to zdb at [301:1037:16ee:23fb:b621:474b:4dc:c34b]:9900
2022-09-05 17:23:01 +02:00: DEBUG renewing stats fd
2022-09-05 17:23:02 +02:00: DEBUG renewing stats fd
2022-09-05 17:23:03 +02:00: DEBUG renewing stats fd
2022-09-05 17:23:04 +02:00: DEBUG connecting to zdb at [301:1037:16ee:23fb:b621:474b:4dc:c34b]:9900
2022-09-05 17:23:04 +02:00: DEBUG renewing stats fd
2022-09-05 17:23:05 +02:00: DEBUG renewing stats fd
2022-09-05 17:23:06 +02:00: DEBUG renewing stats fd
2022-09-05 17:23:07 +02:00: DEBUG connecting to zdb at [301:1037:16ee:23fb:b621:474b:4dc:c34b]:9900
2022-09-05 17:23:07 +02:00: DEBUG renewing stats fd
2022-09-05 17:23:08 +02:00: DEBUG renewing stats fd
2022-09-05 17:23:09 +02:00: DEBUG renewing stats fd
2022-09-05 17:23:10 +02:00: DEBUG connecting to zdb at [301:1037:16ee:23fb:b621:474b:4dc:c34b]:9900
2022-09-05 17:23:10 +02:00: DEBUG renewing stats fd
2022-09-05 17:23:11 +02:00: DEBUG renewing stats fd
2022-09-05 17:23:12 +02:00: DEBUG renewing stats fd
2022-09-05 17:23:13 +02:00: DEBUG connecting to zdb at [301:1037:16ee:23fb:b621:474b:4dc:c34b]:9900
2022-09-05 17:23:13 +02:00: DEBUG renewing stats fd
2022-09-05 17:23:14 +02:00: DEBUG renewing stats fd
2022-09-05 17:23:15 +02:00: DEBUG renewing stats fd
2022-09-05 17:23:16 +02:00: DEBUG connecting to zdb at [301:1037:16ee:23fb:b621:474b:4dc:c34b]:9900
2022-09-05 17:23:16 +02:00: DEBUG renewing stats fd
```

2 - starting local zdb, in `/home/sameh/zdb_temp`, using

```sh
sudo zdb --mode=seq --hook=/home/sameh/projects/0-stor_v2/hook.sh --verbose
```

with this hook file

```sh
#!/usr/bin/env -S setsid --wait /bin/sh

set -x

echo args "$@"

action="$1"
instance="$2"
zstorconf="/home/sameh/projects/0-stor_v2/zstor_config.toml"
zstorbin="/usr/local/bin/zstor_v2"
zstorindex="/home/sameh/zdb_temp/zdb-index"
zstordata="/home/sameh/zdb_temp/zdb-data"

restore_namespace () {
    indexdir="$zstorindex/$1"
    datadir="$zstordata/$1"
    ci=0 # current index

    ${zstorbin} -c ${zstorconf} retrieve --file "$indexdir/zdb-namespace"
    while true; do
        indexpath="$indexdir/i$ci"
        ${zstorbin} -c ${zstorconf} retrieve --file "$indexpath"
        if [ $? != 0 ]; then
            if [ $ci != 0 ]; then
                datapath="$datadir/d$(( $ci - 1))"
                ${zstorbin} -c ${zstorconf} retrieve --file "$datapath"
            fi
            break
        fi
        ci=$(( $ci + 1 ))
    done
}

if [ "$action" = "ready" ]; then
    exit 0
fi

# doesn't work because close is not the last hook
# if [ "$action" = "close" ]; then
#     cat /proc/*/comm 2> /dev/null | grep '[h]ook.sh'
#     while ! cat /proc/*/comm | grep '[h]ook.sh' | wc -l | grep -q '^1$'; do
#         # there's another hook other than ourself
#         sleep .1
#     done
#     echo 'all hooks are dead'
#     exit 0
# fi

if [ "$action" = "namespaces-init" ]; then
    restore_namespace zdbfs-meta
    restore_namespace zdbfs-data
    exit 0
fi
# zdbfs-data /data/index/zdbfs-data/i18 /data/data/zdbfs-data/d18 17 18
if [ "$action" = "namespace-closing" ]; then
    namespace="$3"
    ci="$4"
    cd="$5"
    dirty="$6"
    if [ "${namespace}" = "zdbfs-temp" ]; then
        exit 0
    fi
    indexdir=$(dirname $ci)
    datadir=$(dirname $cd)
    lastindex="$indexdir/$ci"
    lastdata="$datadir/$cd"

    ${zstorbin} -c ${zstorconf} store --notblocking -s --file "$ci"
    ${zstorbin} -c ${zstorconf} store --notblocking -s --file "$cd"
    
    for index in $dirty; do
        indexfile="$indexdir/i$index"
        ${zstorbin} -c ${zstorconf} store --notblocking -s --file "$indexfile"
    done
    exit 0
fi

if [ "$action" = "namespace-created" ] || [ "$action" = "namespace-updated" ]; then
    if [ "$3" = "zdbfs-temp" ]; then
        # skipping temporary namespace
        exit 0
    fi
    file="$zstorindex/$3/zdb-namespace"

    # backup zdb-namespace file
    ${zstorbin} -c ${zstorconf} store --notblocking -s --file "$file"

    exit 0
fi

if [ "$action" = "jump-index" ]; then
    
    namespace=$(basename $(dirname $3))
    if [ "${namespace}" = "zdbfs-temp" ]; then
        # skipping temporary namespace
        exit 0
    fi

    tmpdir=$(mktemp -p /tmp -d zdb.hook.tmp.XXXXXXXX)
    dirbase=$(dirname $3)

    # upload dirty index files
    for dirty in $5; do
        file=$(printf "i%d" $dirty)
        cp ${dirbase}/${file} ${tmpdir}/
    done
    cp "$3" ${tmpdir}/
    ${zstorbin} -c ${zstorconf} store --notblocking -s -d -f ${tmpdir} -k ${dirbase} &

    exit 0
fi

if [ "$action" = "jump-data" ]; then
    namespace=$(basename $(dirname $3))
    if [ "${namespace}" = "zdbfs-temp" ]; then
        # skipping temporary namespace
        exit 0
    fi

    # backup data file
    ${zstorbin} -c ${zstorconf} store --notblocking -s --file "$3"

    exit 0
fi

if [ "$action" = "missing-data" ]; then
    # restore missing data file
    ${zstorbin} -c ${zstorconf} retrieve --file "$3"
    exit $?
fi

# unknown action
exit 1
```
here is the output
```sh
[       0.000062][*] 0-db engine, v2.0.4 (commit v2.0.4)                                                                  
[       0.000147][*] 0-db server, v2.0.4 (commit v2.0.4)                                                                  
[       0.000160][+] system: acceleration engine: sse42                                                                   
[       0.000185][+] system: external hook: /home/sameh/projects/0-stor_v2/hook.sh                                        
[       0.000196][+] system: verbose mode enabled                                                                         
[       0.000204][+] system: running mode: sequential keys                                                                
[       0.000212][+] system: data chunk size: 256.00 MB                                                                   
[       0.000222][+] system: instance id: 858760379                                                                       
[       0.000231][+] system: setting up environments                                                                      
[       0.000249][+] system: creating datapath: ./zdb-data                                                                
[       0.000373][+] system: creating indexpath: ./zdb-index                                                              
[       0.000463][+] bootstrap: checking lockfile: ./zdb-index/.lockfile                                                  
[       0.000511][+] bootstrap: checking lockfile: ./zdb-data/.lockfile                                                   
[       0.000553][+] namespaces: pre-initializing                                                                         
[       0.000567][+] hook: creating hook <namespaces-init>                                                                
[       0.000577][+] hooks: looking for an empty slot                                                                     
[       0.000717][+] hooks: waiting for hook to finish: 348545                                                            
[       0.000788][+] hooks: executing hook </home/sameh/projects/0-stor_v2/hook.sh> (6 args)                              
+ echo args namespaces-init tcp://:::9900 ./zdb-index ./zdb-data                                                          
args namespaces-init tcp://:::9900 ./zdb-index ./zdb-data                                                                 
+ action=namespaces-init                   
+ instance=tcp://:::9900                                                                                         [75/1856]
+ zstorconf=/home/sameh/projects/0-stor_v2/zstor_config.toml
+ zstorbin=/usr/local/bin/zstor_v2
+ zstorindex=/home/sameh/zdb_temp/zdb-index
+ zstordata=/home/sameh/zdb_temp/zdb-data
+ [ namespaces-init = ready ]
+ [ namespaces-init = namespaces-init ]
+ restore_namespace zdbfs-meta 
+ indexdir=/home/sameh/zdb_temp/zdb-index/zdbfs-meta
+ datadir=/home/sameh/zdb_temp/zdb-data/zdbfs-meta
+ ci=0
+ /usr/local/bin/zstor_v2 -c /home/sameh/projects/0-stor_v2/zstor_config.toml retrieve --file /home/sameh/zdb_temp/zdb-ind
ex/zdbfs-meta/zdb-namespace   
Zstor error: error during metadata: zdb metadata error while: ZDB BACKEND: ZDB at [302:9e63:7d43:b742:469d:3ec2:ab15:f75e]
:9900 41-7478-hamada2, error operation READ caused by missing key 2f68616d6164612f6d6574612f366135353739663633333239373534
3738363636366538616635333535633430                           
+ true
+ indexpath=/home/sameh/zdb_temp/zdb-index/zdbfs-meta/i0
+ /usr/local/bin/zstor_v2 -c /home/sameh/projects/0-stor_v2/zstor_config.toml retrieve --file /home/sameh/zdb_temp/zdb-ind
ex/zdbfs-meta/i0              
Zstor error: error during metadata: zdb metadata error while: ZDB BACKEND: ZDB at [302:9e63:7d43:b742:469d:3ec2:ab15:f75e]
:9900 41-7478-hamada2, error operation READ caused by missing key 2f68616d6164612f6d6574612f363661363837336139396133366539
6531376434323132353663353537623632                           
+ [ 1 != 0 ]
+ [ 0 != 0 ]                                                                                                     [51/1856]
+ break
+ restore_namespace zdbfs-data 
+ indexdir=/home/sameh/zdb_temp/zdb-index/zdbfs-data
+ datadir=/home/sameh/zdb_temp/zdb-data/zdbfs-data
+ ci=0
+ /usr/local/bin/zstor_v2 -c /home/sameh/projects/0-stor_v2/zstor_config.toml retrieve --file /home/sameh/zdb_temp/zdb-ind
ex/zdbfs-data/zdb-namespace   
Zstor error: error during metadata: zdb metadata error while: ZDB BACKEND: ZDB at [302:9e63:7d43:b742:469d:3ec2:ab15:f75e]
:9900 41-7478-hamada2, error operation READ caused by missing key 2f68616d6164612f6d6574612f303262336166373662663634366265
6631393537656536636530373734623062                           
+ true
+ indexpath=/home/sameh/zdb_temp/zdb-index/zdbfs-data/i0
+ /usr/local/bin/zstor_v2 -c /home/sameh/projects/0-stor_v2/zstor_config.toml retrieve --file /home/sameh/zdb_temp/zdb-ind
ex/zdbfs-data/i0              
Zstor error: error during metadata: zdb metadata error while: ZDB BACKEND: ZDB at [302:9e63:7d43:b742:469d:3ec2:ab15:f75e]
:9900 41-7478-hamada2, error operation READ caused by missing key 2f68616d6164612f6d6574612f336635386334636430363537393163
3764653362353964663335303239393364                           
+ [ 1 != 0 ]
+ [ 0 != 0 ]
+ break
+ exit 0
[       1.234327][+] namespaces: initializing
[       1.234383][+] namespaces: loading 'default'
[       1.234416][+] namespaces: checking index [./zdb-index/default]                                            [27/1856]
[       1.234690][+] namespaces: checking data [./zdb-data/default]
[       1.234960][+] namespaces: updating header
[       1.237435][+] index: initializing
[       1.237495][+] index: allocating dirty length: 1 bytes
[       1.237521][+] index loader: allocating sequential buffer map
[       1.237553][+] index: loader: fresh database created in sequential mode
[       1.237572][+] index: loader: initializing default seqmap
[       1.237588][+] index seq: mapping id 0 to file 0
[       1.237679][+] index: loading file: ./zdb-index/default/i0
[       1.237800][+] index: creating empty file
[       1.237819][+] index: writing 29 bytes on fd 5
[       1.237880][+] index: running mode: sequential keys
[       1.237899][+] index: writing 29 bytes on fd 5
[       1.237920][+] index: created at: 2022-09-05 17:26:59
[       1.238098][+] index: last open: 2022-09-05 17:26:59
[       1.238142][+] index: populating: ./zdb-index/default/i0
[       1.238163][+] index: loading in memory file: 0.00 MB
[       1.238194][+] index: last offset: 0
[       1.238217][+] index: loader: index is healthy
[       1.238255][+] index: active file: ./zdb-index/default/i0
[       1.238270][+] index: load: 0 entries
[       1.238293][+] index: datasize: 0.00 MB (0 bytes)
[       1.238312][+] index: raw usage: 0.0 KB (0 bytes)
[       1.238323][+] index seq: seqid 0 -> file 0                                                                 [3/1856]
[       1.238415][+] data: writing 28 bytes to fd 6
[       1.238468][+] data: wrote 28 bytes to fd 6
[       1.238512][+] data: reading file, finding last entry
[       1.238540][+] data: entries read: 0, last offset: 0
[       1.238567][+] data: active file: ./zdb-data/default/d0 
[       1.238664][+] namespaces: 0 extra namespaces loaded
[       1.238687][+] network: looking for: host: ::, port: 9900
[       1.238769][+] listen request: tcp://:::9900 (fd: 7)
[       1.238811][+] listening on socket 7
[       1.238830][+] hook: starting and waiting initial hook event (ready)
[       1.238846][+] hook: creating hook <ready>
[       1.238865][+] hooks: looking for an empty slot
[       1.239101][+] hooks: waiting for hook to finish: 348557
[       1.239216][+] hooks: executing hook </home/sameh/projects/0-stor_v2/hook.sh> (4 args)
+ echo args ready tcp://:::9900
args ready tcp://:::9900
+ action=ready
+ instance=tcp://:::9900
+ zstorconf=/home/sameh/projects/0-stor_v2/zstor_config.toml
+ zstorbin=/usr/local/bin/zstor_v2
+ zstorindex=/home/sameh/zdb_temp/zdb-index
+ zstordata=/home/sameh/zdb_temp/zdb-data
+ [ ready = ready ]
+ exit 0
[       1.245846][+] hook: external hook initialized correctly
```

3 - finally i'm lunching the zdbfs using
```sh
zdbfs -o allow_other -o autons -o auto_unmount /mnt/zdbfs
```

which will cause the zstor process to panicked imedialty, in an infine loop.
```
thread 'main' panicked at 'assertion failed: raw_key.len() == std::mem::size_of::<Key>()', zstor/src/zdb.rs:706:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'assertion failed: raw_key.len() == std::mem::size_of::<Key>()', zstor/src/zdb.rs:706:13
thread 'main' panicked at 'assertion failed: raw_key.len() == std::mem::size_of::<Key>()', zstor/src/zdb.rs:706:13
thread 'main' panicked at 'assertion failed: raw_key.len() == std::mem::size_of::<Key>()', zstor/src/zdb.rs:706:13
thread 'main' panicked at 'assertion failed: raw_key.len() == std::mem::size_of::<Key>()', zstor/src/zdb.rs:706:13
....
```

here is the zstor.log after the panic

```
2022-09-05 17:35:15 +02:00: DEBUG Handling new client connection from (unnamed)
2022-09-05 17:35:15 +02:00: DEBUG scheduler received a command ZstorSchedulerMessage { cmd: ZstorCommand(Store(Store { file: "/home/sameh/zdb_temp/zdb-index/zdbfs-meta/zdb-namespace", key_path: None, save_failure: true, delete: false, blocking: false })), blocking: false, priority: 1, response: Sender { inner: Some(Inner { state: State { is_complete: false, is_closed: true, is_rx_task_set: false, is_tx_task_set: false } }) } } with prio 1
2022-09-05 17:35:15 +02:00: DEBUG the scheduler forwarding command Store(Store { file: "/home/sameh/zdb_temp/zdb-index/zdbfs-meta/zdb-namespace", key_path: None, save_failure: true, delete: false, blocking: false })
2022-09-05 17:35:15 +02:00: DEBUG encoding file "/home/sameh/zdb_temp/zdb-index/zdbfs-meta/zdb-namespace" with key path "/home/sameh/zdb_temp/zdb-index/zdbfs-meta/zdb-namespace"
2022-09-05 17:35:15 +02:00: DEBUG file checksum: 4ab1d2c1bb4be398cd9726251442fc78 ("/home/sameh/zdb_temp/zdb-index/zdbfs-meta/zdb-namespace")
2022-09-05 17:35:15 +02:00: DEBUG Finding backend config
2022-09-05 17:35:15 +02:00: DEBUG Handling new client connection from (unnamed)
2022-09-05 17:35:15 +02:00: DEBUG connecting to zdb at [301:b989:8977:ff23:3f30:ee86:fc5b:ecd7]:9900
2022-09-05 17:35:15 +02:00: DEBUG connecting to zdb at [302:9e63:7d43:b742:469d:3ec2:ab15:f75e]:9900
2022-09-05 17:35:15 +02:00: DEBUG connecting to zdb at [301:1037:16ee:23fb:b621:474b:4dc:c34b]:9900
2022-09-05 17:35:15 +02:00: DEBUG connecting to zdb at [300:487a:7ea1:5b4e:e244:ef5d:6f66:1670]:9900
2022-09-05 17:35:15 +02:00: DEBUG renewing stats fd
2022-09-05 17:35:16 +02:00: DEBUG found valid backend configuration
2022-09-05 17:35:17 +02:00: ERROR failed to process store command error during waiting for async task completion: panic, queueing a retry
...
```

if I clean local zdb and start over I'll get the same panic, however, if I left the local data and restart all processes in order again it won't panic.

but it still does not work. here is the zstor.log content after copying some files to zdbfs mount directory

```
2022-09-05 17:49:11 +02:00: DEBUG scheduler received a command ZstorSchedulerMessage { cmd: ZstorCommand(Store(Store { file: "/tmp/zdb.hook.tmp.8CLxb3JA", key_path: Some("./zdb-index/zdbfs-data"), save_failure: true, delete: true, blocking: false })), blocking: false, priority: 1, response: Sender { inner: Some(Inner { state: State { is_complete: false, is_closed: true, is_rx_task_set: false, is_tx_task_set: false } }) } } with prio 1
2022-09-05 17:49:11 +02:00: DEBUG the scheduler forwarding command Store(Store { file: "/tmp/zdb.hook.tmp.8CLxb3JA", key_path: Some("./zdb-index/zdbfs-data"), save_failure: true, delete: true, blocking: false })
2022-09-05 17:49:11 +02:00: ERROR failed to process store command error during accessing local storage for could not create temp file: No such file or directory (os error 2), queueing a retry
2022-09-05 17:49:11 +02:00: DEBUG the scheduler forwarding command Store(Store { file: "/tmp/zdb.hook.tmp.8CLxb3JA", key_path: Some("./zdb-index/zdbfs-data"), save_failure: true, delete: true, blocking: false })
2022-09-05 17:49:11 +02:00: DEBUG Handling new client connection from (unnamed)
2022-09-05 17:49:11 +02:00: ERROR failed to process store command error during accessing local storage for could not create temp file: No such file or directory (os error 2), queueing a retry
2022-09-05 17:49:11 +02:00: DEBUG scheduler received a command ZstorSchedulerMessage { cmd: ZstorCommand(Store(Store { file: "./zdb-data/zdbfs-data/d0", key_path: None, save_failure: true, delete: false, blocking: false })), blocking: false, priority: 1, response: Sender { inner: Some(Inner { state: State { is_complete: false, is_closed: true, is_rx_task_set: false, is_tx_task_set: false } }) } } with prio 1
2022-09-05 17:49:11 +02:00: DEBUG the scheduler forwarding command Store(Store { file: "/tmp/zdb.hook.tmp.8CLxb3JA", key_path: Some("./zdb-index/zdbfs-data"), save_failure: true, delete: true, blocking: false })
2022-09-05 17:49:11 +02:00: ERROR failed to process store command error during accessing local storage for could not create temp file: No such file or directory (os error 2), queueing a retry
...
```

**Comment by LeeSmet** [comment]
fixed in 5b7a311c881a820592ad79c078c4dbec44e63bd8
